kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.services.gateway.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.gateway.label }}
  ports:
  - protocol: TCP
    port: {{ .Values.gateway.containerPort }}  
    nodePort: {{ .Values.services.gateway.nodePort }} 
  type: NodePort
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.services.payroll.name }} 
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.payroll.label }} 
  ports:
  - protocol: TCP
    port: {{ .Values.payroll.containerPort }}  
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.services.timesheet.name }} 
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.timesheet.label }} 
  ports:
  - protocol: TCP
    port: {{ .Values.timesheet.containerPort }} 
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.services.neo4j.name }} 
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: neo4j-db
  ports:
  - name: http
    protocol: TCP
    port: 7474
    nodePort: 30002  
  - name: bolt
    protocol: TCP
    port: 7687
    nodePort: 30001  
  type: NodePort