apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
  - name: nginx-container
    image: ngnix:latest
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-service
spec:
  selector:
    apps: nginx
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30081
  type: NodePort