apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-service-cluster-binding
subjects:
- kind: ServiceAccount
  name: reader-pod-cluster-level
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-service-cluster-role
  apiGroup: rbac.authorization.k8s.io