apiVersion: v1
kind: ServiceAccount
metadata:
  name: reader-pod-cluster-level
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-service-cluster-binding
subjects:
- kind: ServiceAccount
  name: reader-pod-cluster-level
  namespace: default
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: pod-service-cluster-role
  apiGroup: rbac.authorization.k8s.io