apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-service-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: pods-only-sa
  apiGroup: ""
roleRef:
  kind: Role
  name: pods-only-role
  apiGroup: rbac.authorization.k8s.io