apiVersion: batch/v1
kind: CronJob
metadata:
  name: batch-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: batch-job
            image: busybox:1.28
            args:
            - /bin/sh
            - -c
            - date; echo Batch Job is Running
          restartPolicy: OnFailure