apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web-app-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-react-container
        image: adityadev01/web-react:1.0
