kind: Service
apiVersion: v1
metadata:
  name: web-app-service
spec:
  selector:
    app: web-app
  ports:
  - protocol: TCP
    port: 8080 # internal port used by service to redirect traffic to target container port
    targetPort: 80 # container port to target, this is optional value of port is used 
    nodePort: 30080 # external port 
  type: NodePort
