apiVersion: v1
kind: Pod
metadata:
  name: small-pod-1
  namespace: k8s-lab
spec:
  containers:
  - name: httpd-container
    image: httpd:2.4.48
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
