apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neo4j-sts
  labels:
    app: neo4j-db
spec:
  selector:
    matchLabels:
      app: neo4j-db
  serviceName: neo4j-db
  replicas: 1
  template:
    metadata:
      labels:
        app: neo4j-db
    spec:
      volumes:
        - name: data-volume
          hostPath:
            path: /tmp/2/neo4j
      containers:
      - name: neo4j-pod
        image: neo4j
        volumeMounts:
        - name: data-volume
          mountPath: /data
---
kind: Service
apiVersion: v1
metadata:
  name: neo4j-db
spec:
  selector:
    app: neo4j-db
  ports:
  - name: http
    protocol: TCP
    port: 7474
    nodePort: 30001 
  - name: bolt
    protocol: TCP
    port: 7687
    nodePort: 30002
  type: NodePort