apiVersion: v1
kind: Pod
metadata:
  labels:
    app: httpd-custom
  name: http-custom-pod
spec:
  containers:
  - name: liveness
    image: adityadev01/httpd-custom:1.0
    livenessProbe:
      httpGet:
        path: /datetime.html
        port: 80
      initialDelaySeconds: 4
      periodSeconds: 3
      failureThreshold: 2
---
kind: Service
apiVersion: v1
metadata:
  name: httpd-custom-service
spec:
  selector:
    app: httpd-custom
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30090
  type: NodePort