apiVersion: v1
kind: Secret
metadata:
  name: neo4j-config
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  NEO4J_URI: {{ .Values.neo4j.uri }}
data:
  NEO4J_USER: {{ .Values.neo4j.user }}
  NEO4J_PASSWORD: {{ .Values.neo4j.password }} 