apiVersion: v1
kind: Secret
metadata:
  name: secret-neo4j-config
type: Opaque # Secret is unstructured as compared to structured types like ServiceAccount
data:
  NEO4J_URI: XXXXXXX
  NEO4J_USER: bmVvNGo=
  NEO4J_PASSWORD: XXXXXXXXXXXXXXXXXX
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server-deployment
  labels:
    app: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
      - name: api-server-container
        image: adityadev01/api-server:1.0
        envFrom:
        - secretRef:
            name: secret-neo4j-config
        ports:
        - containerPort: 4001
---        
kind: Service
apiVersion: v1
metadata:
  name: app-server-service
spec:
  selector:
    app: api-server
  ports:
  - protocol: TCP
    port: 4001  
    nodePort: 30082
  type: NodePort
