apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-app
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: "nginx"
  replicas: 3
  updateStrategy:
    type: OnDelete
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.19 
        readinessProbe:
          exec:
            command:
              - "sh"
          initialDelaySeconds: 5
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: persistent-store
          mountPath: /usr/share/nginx/html
      volumes:
        - name: persistent-store
          hostPath:
            path: /tmp/store 
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx