apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-app
  labels:
    app: gateway-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gateway-app
  template:
    metadata:
      name: gateway-pod
      labels:
        app: gateway-app
    spec:
      containers:
      - name: gateway-container
        image: adityadev01/hr-gateway:2.0 
        ports:
          - name: gateway-port
            containerPort: 8080
        startupProbe:
          httpGet:
            path: /api/ready
            port: gateway-port
          periodSeconds: 60
          failureThreshold: 2
        readinessProbe:
          httpGet:
            path: /api/ready
            port: gateway-port
        livenessProbe:
          httpGet:
            path: /api/health
            port: gateway-port
          periodSeconds: 8
          failureThreshold: 1
          successThreshold: 1  
---
kind: Service
apiVersion: v1
metadata:
  name: hr-gateway
spec:
  selector:
    app: gateway-app
  ports:
  - protocol: TCP
    port: 8080  
    nodePort: 30081 
  type: NodePort
