apiVersion: v1
kind: ConfigMap
metadata:
  name: neo4j-config
  namespace: default
data:
  NEO4J_URI: neo4j+s://51e7fb01.databases.neo4j.io
  NEO4J_USER: neo4j
  NEO4J_PASSWORD: vJaAjE_RGl-dAlx6Lk5MfKk7cEmMQBzzXhtOWfoMDB8
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server-deployment
  labels:
    app: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
      - name: api-server-container
        image: adityadev01/api-server:1.0
        envFrom:
        - configMapRef:
            name: neo4j-config
        ports:
        - containerPort: 4001
---        
kind: Service
apiVersion: v1
metadata:
  name: app-server-service
spec:
  selector:
    app: api-server
  ports:
  - protocol: TCP
    port: 4001  
    nodePort: 30082
  type: NodePort
