apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: headless-svc
spec:
  clusterIP: None 
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080        
---
apiVersion: v1
kind: Service
metadata:
  name: regular-service
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080