apiVersion: v1
kind: Pod
metadata:
  name: big-pod
  namespace: k8s-lab
spec:
  containers:
  - name: httpd-container
    image: httpd:2.4.48
    resources:
      requests:
        cpu: "501m"
        memory: "257Mi"
      limits:
        cpu: "2000m"
        memory: "2000Mi"