apiVersion: v1
kind: LimitRange
metadata:
  name: lab-limitrange
  namespace: k8s-lab
spec:
  limits:
    - default: # default limits
        cpu: 500m
        memory: 512Mi
      defaultRequest: # default request
        cpu: 250m
        memory: 256Mi
      min: # minimum limit should be higher than this if specified for container 
        cpu: 250m
        memory: 128Mi
      max: # maximum limit should be lower than this if specified for container
        cpu: 1500m # this becomes the default if defaults not set
        memory: 1.5Gi
      type: Container # type can be container or pod