apiVersion: v1
kind: Pod
metadata:
  name: with-pod-affinity
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
      # pod can schedule onto a node only if that node 
      # has at least one already-running pod with a label 
      # that has the key security and value S1
          matchExpressions:
          - key: security
            operator: In # matchExpression can be In, NotIn, Exists, or DoesNotExist
            values:
            - S1
        topologyKey: topology.kubernetes.io/zone
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            # pod prefers to not schedule onto a node if that node 
            # is already running a pod with label having key security 
            # and value S2
            matchExpressions:
            - key: security
              operator: In
              values:
              - S2
          topologyKey: topology.kubernetes.io/zone
  containers:
  - name: with-pod-affinity
    image: k8s.gcr.io/pause:2.0